---

mongodb_repository:
  "2.6": "http://downloads-distro.mongodb.org/repo/redhat/os/$basearch/"
  "3.0": "https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.0/$basearch/"
  "3.2": "https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.2/$basearch/"
  "3.4": "https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.4/$basearch/"

mongodb_repository_gpgkey:
  "3.2": "https://www.mongodb.org/static/pgp/server-3.2.asc"
  "3.4": "https://www.mongodb.org/static/pgp/server-3.4.asc"

mongodb_pidfile_path: "{{ '/var/run/mongodb/mongod.pid' if ('mongodb-org' in mongodb_package) else '' }}"
