---
# defaults file for kibatic.traefik
traefik_install_dir: /usr/bin
traefik_log_dir: /var/log/traefik
traefik_binary_url: https://github.com/containous/traefik/releases/download/v1.4.4/traefik_linux-amd64
traefik_binary_checksum: sha256:24f2afbaa6d86af9e9a00e854db672715eb4c4eef80d40bad15f917525d61292
traefik_bin_path: "{{ traefik_install_dir }}/traefik"
traefik_config_file: /etc/traefik.toml
traefik_template: traefik.toml
traefik_systemd_unit_template: traefik.service
traefik_systemd_unit_dest: /etc/systemd/system/traefik.service
traefik_update: no
