---
# This play is necessary, because we need to know IP addresses of defined interfaces
- hosts: consul_servers
  tags:
  - consul_servers
  gather_facts: true
  tasks:
  - name: "only gather facts"
    debug:
      msg: "only gather facts"

# install servers
# assuming that we have 3 servers, we can always take one down without compromising the consul cluster
- hosts: consul_servers
  serial: 1
  become: True
  tags:
  - consul_servers
  roles:
  - role: rattermeyer.consul
    consul_iface: enp0s8
    consul_group_name: consulhosts
    consul_encrypt_key: "b42sY2S3B5EbhrF5UMtI5g=="
    consul_acl_enable: True
    consul_acl_master_token_display: True
    consul_acl_replication_token_display: True
    consul_cleanup: False
    consul_tls_enable: True
    consul_tls_src_dir: /home/vagrant/pki
    consul_tls_ca_crt: "ca.pem"
    consul_tls_crt: "consul.{{ ansible_hostname }}.localdomain.pem"
    consul_tls_key: "consul.{{ ansible_hostname }}.localdomain-key.pem"
    consul_http_bind_address: 127.0.0.1

# install clients
# clients can be updated / processed /restarted in parallel
- hosts: consul_clients
  tags:
  - consul_clients
  roles:
  - role: rattermeyer.consul
    serial: 1
    become: True
    consul_encrypt_key: "b42sY2S3B5EbhrF5UMtI5g=="
    consul_iface: enp0s8
    consul_group_name: consulhosts
    consul_tls_ca_crt: "ca.pem"
    consul_tls_crt: "consul-{{ ansible_hostname }}.pem"
    consul_tls_key: "consul-{{ ansible_hostname }}-key.pem"
    consul_http_bind_address: 127.0.0.1
