- hosts: dockerhosts
  pre_tasks:
  - name: "install aufs"
    become: True
    apt:
      name: "linux-image-extra-{{ansible_kernel}}"
  roles:
    - role: rattermeyer.docker
      pip_version_docker_compose: 1.9.0
      become: True
