---
- hosts: all
  strategy: free
  become: True
  gather_facts: False
  tasks:
  - name: "convert to nearby mirror"
    replace:
      dest: "/etc/apt/sources.list"
      regexp: "http://us.archive.ubuntu.com/ubuntu/"
      replace: "mirror://mirrors.ubuntu.com/mirrors.txt"
  - name: "update cache"
    apt:
      update_cache: true
      cache_valid_time: 86400
