- hosts: nomadhosts
  pre_tasks:
  - name: install archive handlers
    apt:
      name: "{{ item }}"
    with_items:
    - unzip
    - tar
  roles:
    - role: rattermeyer.nomad
      nomad_iface: 'enp0s8'
