---
- name: reload systemd configuration
  command: systemctl daemon-reload
  become: True

- name: restart graylog-server
  service:
    name: 'graylog-server'
    state: restarted
    enabled: yes
  become: True
