---
- hosts: controller
  tasks:
  - name: "install tools"
    become: True
    package:
      name: "{{ item }}"
    with_items:
    - tar
    - unzip
- include: playbooks/pki.yml
  when: pki_create == True

- include: playbooks/fix-mirror.yml
- include: playbooks/servicediscovery.yml
- include: playbooks/docker.yml
- include: playbooks/clusterscheduler.yml
- include: playbooks/monitoring.yml
- include: playbooks/nomad-ui.yml
