---

dependencies: []

galaxy_info:
  author: Sergei Antipov
  company: 2GIS
  description: Manage MongoDB with authentication and replica sets
  license: GPLv2
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
  - name: Debian
    versions:
    - wheezy
  - name: EL
    versions:
      - 6
      - 7
  galaxy_tags:
  - database
  - database:nosql
